config/routes.rb
Setlister::Application.routes.draw do
  devise_for :users

  resources :songs
  resources :setlist_songs

  get "groups/new" => "groups#new"
  resources :groups, :path => "/", :except => [:new, :index] do
    resources :songs
    resources :setlists do
      member do
        get :slideshow
      end
    end
  end

  root :to => 'home#index'
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :setlists
  has_many :songs

  has_many :user_groups
  has_many :users, :through => :user_groups

  attr_accessible :name

  validates :name, :uniqueness => { :case_sensitive => false }

  def to_param
    name.downcase.squish.gsub( /\s/, '_' )
  end
end

app/models/setlist.rb
class Setlist < ActiveRecord::Base
  attr_accessible :title, :setlist_songs_attributes, :print, :print_without_capo

  has_many :setlist_songs
  has_many :songs, :through => :setlist_songs

  accepts_nested_attributes_for :setlist_songs
end

app/models/setlist_song.rb
class SetlistSong < ActiveRecord::Base
  attr_accessible :song_id, :setlist_id, :data_key, :capo, :position

  belongs_to :setlist
  belongs_to :song

  default_scope order("position")

  def key
    data_key
  end

  def key=(new_key)
    write_attribtue(:key, new_key)
  end

  def title
    song.title
  end

  def artist
    song.artist
  end

  def year
    song.year
  end

  def license
    song.license
  end

  def text
    song.text
  end

  def info
    song.info
  end

  def slides
    song.slides
  end

  def spotify_uri
    song.spotify_uri
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :title, :artist, :year, :text, :data_key, :spotify_uri, :capo, :info, :year_string, :license

  has_many :setlist_songs
  has_many :setlists, :through => :setlist_songs

  def key
    data_key
  end

  def key=(new_key)
    write_attribute :data_key, new_key
  end

  def slides
      chord_regex = /\b([A-G][b\#]?(2|5|6|7|9|11|13|6\/9|7\-5|7\-9|7\#5|7\#9|7\+5|7\+9|7b5|7b9|7sus2|7sus4|add2|add4|add9|aug|dim|dim7|m\/maj7|m6|m7|m7b5|m9|m11|m13|maj7|maj9|maj11|maj13|mb5|m|sus|sus2|sus4)*)(?=[^A-z])/
      slides = text.gsub( chord_regex, '' ).gsub( /\//, '' ).gsub( /\([^\(\)]*\)/, '' ).gsub( /_/, '' ).gsub( /\r\n[\s]*\r\n/, "\n" ).split( /[A-Z\s0-9]+\:/ )
      slides.map do |s|
        s.strip
      end
  end

  def year_string
    year ? year.strftime("%Y") : ""
  end

  def year_string=(year_str)
    # Explicitly adding the rest of the date string so Time.parse works
    self.year = Time.parse("#{year_str}-01-01 00:00:00")
  rescue ArgumentError
    @year_invalid = true
  end

  def validate
    errors.add(:year, "is invalid") if @year_invalid
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_groups
  has_many :groups, :through => :user_groups

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  respond_to :html, :json

  def new
    @group = Group.new
  end

  def create
    group_params = params[:group]
    @group = Group.new group_params
    @group.users << current_user

    if @group.save
      respond_with @group
    else
      redirect_to new_groups_path
    end
  end

  def show
    @group = Group.where("lower(name) = ?", params[:id].gsub( /_/, ' ' ).downcase).first
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
    @user = User.new
  end
end

app/controllers/setlist_songs_controller.rb
class SetlistSongsController < ApplicationController
  before_filter :is_admin
  respond_to :html, :json

  def create
    @setlist_song = SetlistSong.new(params[:setlist_song])
    @setlist = Setlist.find(params[:setlist_song][:setlist_id])
    last_song = @setlist.setlist_songs.order("position ASC").last
    if last_song
      @setlist_song.position = ( last_song.position ? last_song.position : 0 ) + 1
    end

    @setlist_song.save

    respond_with @setlist_song
  end

  def destroy
    @setlist_song = SetlistSong.find(params[:id])

    setlist = @setlist_song.setlist
    @setlist_song.destroy

    # renumber each setlist_song
    setlist.setlist_songs.each_with_index do |song, idx|
      song.position = idx + 1
      song.save
    end

    redirect_to setlist_path(setlist)
  end

  private
  def is_admin
    if !signed_in? || !current_user.admin?
      flash[:notice] = "You have to be an admin to do that."
      redirect_to root_path
    end
  end
end

app/controllers/setlists_controller.rb
require 'open-uri'
class SetlistsController < ApplicationController
  before_filter :is_admin, :except => [:index, :show, :slideshow]
  before_filter :get_backgrounds, :only => [:slideshow]
  before_filter :group

  respond_to :html, :json

  def new
    @setlist = Setlist.new

    respond_with @setlist
  end

  def create
    @setlist = Setlist.create(params[:setlist])

    redirect_to group_setlists_path(@group)
  end

  def edit
    @setlist = Setlist.find(params[:id])

    respond_with @setlist
  end

  def update
    @setlist = Setlist.find(params[:id])
    @setlist.update_attributes(params[:setlist])

    redirect_to group_setlist_path(@group, @setlist)
  end

  def index
    @setlists = Setlist.order("created_at DESC")

    respond_with @setlists
  end

  def show
    @setlist = Setlist.find(params[:id])

    respond_with @setlist
  end

  def destroy
    @setlist = Setlist.find(params[:id])

    @setlist.destroy

    redirect_to group_setlists_path(@group)
  end

  def slideshow
    @setlist = Setlist.find(params[:id])
    @full = params[:full]

    render :slideshow, :layout => "empty"
  end

  private
  def is_admin
    if !signed_in? || !current_user.admin?
      flash[:notice] = "You have to be an admin to do that."
      redirect_to root_path
    end
  end

  def get_backgrounds
    @backgrounds = []
    Dir.foreach('app/assets/images/ss-backgrounds') do |fname|
      if fname != '..' && fname != '.'
        @backgrounds << fname
      end
    end
  end

  def group
    @group = Group.where("lower(name) = ?", params[:group_id].downcase).first
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :is_admin, :except => [:index, :show]
  before_filter :group

  respond_to :html, :json

  def new
    @song = Song.new

    respond_with @song
  end

  def create
    @song = Song.new(params[:song])

    if @song.save
      redirect_to group_song_path(@group, @song)
    else
      redirect_to new_song_path
    end
  end

  def show
    @song = Song.find(params[:id])

    respond_with @song
  end

  def index
    @songs = Song.order(:title)
    @setlists = Setlist.order("created_at DESC")

    respond_with @songs
  end

  def edit
    @song = Song.find(params[:id])

    respond_with @song
  end

  def update
    @song = Song.find(params[:id])

    if @song.update_attributes(params[:song])
      redirect_to group_song_path(@group, @song)
    else
      redirect_to edit_song_path(@song)
    end
  end

  def destroy
    @song = Song.find(params[:id])

    @song.destroy

    redirect_to group_songs_path(@group)
  end

  private
  def is_admin
    if !signed_in? || !current_user.admin?
      flash[:notice] = "You have to be an admin to do that."
      redirect_to root_path
    end
  end

  def group
    @group = Group.where("lower(name) = ?", params[:group_id].downcase).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_path_helper.rb
module GroupsPathHelper
end

app/views/groups/new.html.erb
<h2>New Group</h2>

<div class="row">
  <%= form_for(@group, :html => { :class => "col-sm-4" }) do |f| %>
    <div class="form-group">
      <%= f.text_field :name, :autofocus => true, :placeholder => "Group Name", :class => "form-control" %>
    </div>

    <div><%= f.submit "Add", :class => "btn btn-primary" %></div>
  <% end %>
</div>

app/views/groups/show.html.erb
<h1 class="page-header">
  <%= @group.name %>
  <%= link_to "New Setlist", new_group_setlist_path(@group), :class => "btn btn-success pull-right" %>
  <%= link_to "New Song", new_group_song_path(@group), :class => "btn btn-primary pull-right" %>
</h1>

<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Most Used Songs
      </div>
      <div class="panel-content">
        <div class="list-group">
          <a href="#" class="list-group-item">Salvation Is Here</a>
          <a href="#" class="list-group-item">Our God</a>
          <a href="#" class="list-group-item">The Time Has Come</a>
        </div>
      </div>
    </div>
    <div class="panel panel-danger">
      <div class="panel-heading">
        All Songs
      </div>
      <div class="panel-content">
        <div class="list-group">
          <a href="#" class="list-group-item">Our God</a>
          <a href="#" class="list-group-item">The Time Has Come</a>
          <a href="#" class="list-group-item">Salvation Is Here</a>
          <a href="#" class="list-group-item">Our God</a>
          <a href="#" class="list-group-item">The Time Has Come</a>
          <a href="#" class="list-group-item">Salvation Is Here</a>
          <a href="#" class="list-group-item">Our God</a>
          <a href="#" class="list-group-item">The Time Has Come</a>
          <a href="#" class="list-group-item">Salvation Is Here</a>
          <a href="#" class="list-group-item">Our God</a>
          <a href="#" class="list-group-item">The Time Has Come</a>
          <a href="#" class="list-group-item">More...</a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="panel panel-success">
      <div class="panel-heading">
        Most Recent Setlists
      </div>
      <div class="panel-content">
        <div class="list-group">
          <a href="#" class="list-group-item">10/22 Sunday</a>
          <a href="#" class="list-group-item">10/15 Wednesday</a>
          <a href="#" class="list-group-item">10/11 Sunday</a>
        </div>
      </div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">
        All Setlists
      </div>
      <div class="panel-content">
        <div class="list-group">
          <a href="#" class="list-group-item">Sunday 10/22</a>
          <a href="#" class="list-group-item">Wednesday 10/11</a>
          <a href="#" class="list-group-item">Sunday 10/22</a>
          <a href="#" class="list-group-item">Sunday 10/15</a>
          <a href="#" class="list-group-item">Wednesday 10/11</a>
          <a href="#" class="list-group-item">Sunday 10/22</a>
          <a href="#" class="list-group-item">Sunday 10/15</a>
          <a href="#" class="list-group-item">Wednesday 10/11</a>
          <a href="#" class="list-group-item">Sunday 10/22</a>
          <a href="#" class="list-group-item">Sunday 10/15</a>
          <a href="#" class="list-group-item">Wednesday 10/11</a>
          <a href="#" class="list-group-item">More...</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Setlister</h1>

<h2>Sign up</h2>

<div class="row">
  <%= form_for(@user, :as => :user, :url => registration_path(:user), :html => { :class => "col-sm-4" }) do |f| %>
    <div class="form-group">
      <%= f.email_field :email, :autofocus => true, :placeholder => "Email", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.password_field :password, :placeholder => "Password", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.password_field :password_confirmation, :placeholder => "Password Again", :class => "form-control" %>
    </div>

    <div><%= f.submit "Sign up", :class => "btn btn-primary" %></div>
  <% end %>
</div>

app/views/layouts/_flyout.html.erb
<div class="flyout add-to-setlist">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Setlister <%= !@page_title.blank? ? "| #{@page_title}" : "" %></title>

  <script src="//use.edgefonts.net/ubuntu-condensed:n4;ubuntu:n3,i3,n4,i4,n5,i5,n7,i7;ubuntu-mono:n4,n7.js"></script>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "print", :media => "print" %>
</head>
<body data-spy="scroll" data-target="#song-nav" class="<%= params[:controller] %>">
  <nav class="navbar navbar-default" role="navigation">
    <div class="shell">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "SETLISTER", root_path, :class => "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Groups <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% current_user.groups.each do |group| %>
                  <li><%= link_to group.name, group_path(group) %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to "Create a Group", groups_new_path %></li>
                <li><%= link_to "Join a Group", "#" %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Profile</a></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "auth" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path, :class => "auth" %></li>
          <% end %>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <main class="shell">
    <%= yield %>
  </main>

  <footer>
    <div class="row shell">
      <div class="col-sm-12">&copy; Setlister&trade; 2013</div>
    </div>
  </footer>
</body>
<%= javascript_include_tag "application" %>
<%= yield :javascripts %>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Setlister</title>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "print", :media => "print" %>
</head>
<body>
  <%= yield %>
</body>
<%= javascript_include_tag "application" %>
<%= yield :javascripts %>
</html>

app/views/setlists/_form.html.erb
<%= form_for(@setlist, :url => group_setlists_path(@group, @setlist)) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :autofocus => true %>
  </div><br /><br />

  <%= f.submit "#{params[:action] == "edit" ? "Edit" : "Add"} Setlist", :class => "button" %>
<% end %>

app/views/setlists/_setlist.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag "key.selector" %>
  <%= javascript_include_tag "jquery.pin" %>
  <%= javascript_include_tag "spotify" %>
  <%= javascript_include_tag "setlists" %>
  <script type="text/javascript" charset="utf-8">
    $( function() {
      $( '.key-selector' ).keySelector();
      $( '.capo-selector' ).keySelector( true );
      Spotify.init();
    });
  </script>
<% end %>

<div id="setlist-id"><%= @setlist.id %></div>

<% if params[:action] == "edit" %>
  <%= form_for(@setlist, :url => group_setlist_path(@group, @setlist)) do |f| %>
  <div class="hidden-form">
    <%= f.fields_for :setlist_songs do |builder| %>
      <div class="song-fields">
        <%= builder.hidden_field :position %>
        <%= builder.hidden_field :data_key %>
        <%= builder.hidden_field :capo %>
      </div>
    <% end %>
  </div>
  <% end %>
<% end %>

<div class="flyout song-info">
  <ul>
    <li class="head">Song Info</li>
  </ul>
  <% @setlist.setlist_songs.each do |song| %>
    <div id="<%= song.title.gsub(' ','-') %>-info" class="song-info-content"><%= song.info ? auto_link(song.info).html_safe : "None" %></div>
  <% end %>
</div>

<div class="builder">
  <h2>
    Setlist: <%= @setlist.title %>
    <% if params[:action] == "edit" %>
      <%= link_to("Save", "#", :class => "save-setlist button") %>
      <%= text_field :setlist, :print, :class => "edit-print" %>
      <%= label :setlist, :print, :class => "edit-print-label" %>
      <%= text_field :setlist, :print_without_capo, :class => "edit-print" %>
      <%= label :setlist, :print_without_capo, :class => "edit-print-label" %>
    <% else %>
      <% button_text = @setlist.print ? "Print (#{@setlist.print})" : "Print" %>
      <%= link_to(button_text, "#", :class => "print-setlist button") %>
      <% button_text = @setlist.print_without_capo ? "Print w/o Capo (#{@setlist.print_without_capo})" : "Print w/o Capo" %>
      <%= link_to(button_text, "#", :class => "print-setlist-without-capo button", :style => "margin-right: 10px") %>
    <% end %>
  </h2>
  <div class="spotify-player" id="spotify-player">
    <iframe src="https://embed.spotify.com/?uri=<%= @setlist.setlist_songs.first ? @setlist.setlist_songs.first.spotify_uri : "" %>" width="100%" height="80" frameborder="0" allowtransparency="true"></iframe>
  </div>
  <div class="builder-inner">
    <table>
      <tr class="header">
        <th width="50"></th>
        <th width="510">Name</th>
        <th width="500">Key</th>
        <th width="60">Capo</th>
        <th width="149">Actions</th>
      </tr>
      <% i = 1 %>
      <% @setlist.setlist_songs.each do |song| %>
      <tr data-old-pos="<%= song.position %>" data-pos="<%= song.position %>">
        <td><input <%= 'disabled="disabled" ' if params[:action] != 'edit' %>type="text" value="<%= i %>" class="order-field" size="1" style="text-align: right"></td>
        <td class="song-name"><%= link_to(song.title, "##{song.title.gsub( ' ', '-' )}-chords", :class => "song-shortcut") %></td>
        <td class="key-selector" data-start="<%= song.key %>" data-key="<%= song.song.key %>" data-song="<%= song.title.gsub( ' ', '-' ) %>-chords"></td>
        <td>
          <select value="<%= song.capo %>" class="capo-selector" id="" name="" data-song="<%= song.title.gsub( ' ', '-' ) %>-chords">
            <option value="0">--</option>
            <% 12.times do |i| %>
              <option <%= 'selected="selected" ' if song.capo == i+1 %>value="<%= i+1 %>"><%= i+1 %></option>
            <% end %>
          </select>
        </td>
        <td class="actions">
          <%= link_to("", song_path(song.song), :class => "icon-eye-open") %>
          <% if signed_in? && current_user.admin? %>
            <%= link_to("", edit_song_path(song.song), :class => "icon-pencil") %>
            <%= link_to("", setlist_song_path(song), :class => "icon-trash", :method => "delete", :confirm => "Are you sure?") %>
          <% end %>
          <%= link_to("", "#", :class => "icon-headphones", :"data-spotify-uri" => song.spotify_uri) %>
          <% if !song.info.blank? %>
            <%= link_to("", "#", :class => "icon-info-sign", :"data-info" => song.title.gsub(' ', '-')) %>
          <% end %>
        </td>
      </tr>
      <% i += 1 %>
      <% end %>
    </table>
  </div>
</div>

<% @setlist.setlist_songs.each do |song| %>
<div class="song">
  <h2 data-header="<%= song.title.gsub( ' ', '-' ) %>-chords">
    <%= song.title %>
    <%= link_to("", "#", :class => "icon-headphones", :"data-spotify-uri" => song.spotify_uri) %>
  </h2>
  <pre id="<%= song.title.gsub( ' ', '-' ) %>-chords"><%= song.text %></pre>
  <div class="meta">
    <%= song.artist %> <%= !song.year.blank? ? song.year.strftime('%Y') : '' %>
    <span class="license"><%= song.license %></span>
  </div>
</div>
<% end %>

app/views/setlists/edit.html.erb
<% content_for :javascripts do %>
  <script type="text/javascript" charset="utf-8">
    $(function() {
      $( '.builder-inner' ).pin();
    });
  </script>
<% end %>

<%= render "setlist" %>

app/views/setlists/index.html.erb
<h1 class="page-header">Setlists</h1>
<div class="builder">
  <div class="builder-inner">
    <table class="table table-bordered table-striped">
      <tr>
        <th width="50"></th>
        <th width="1110">Name</th>
        <th width="149">Actions</th>
      </tr>
      <% i = 1 %>
      <% @setlists.each do |setlist| %>
      <tr>
        <td><%= i %>.</td>
        <td class="setlist-name"><%= link_to(setlist.title, group_setlist_path(@group, setlist)) %></td>
        <td class="actions">
          <%= link_to("", group_setlist_path(@group, setlist), :class => "icon-eye-open") %>
          <%= link_to("", edit_group_setlist_path(@group, setlist), :class => "icon-pencil") %>
          <%= link_to("", group_setlist_path(@group, setlist), :class => "icon-trash", :method => "delete", :confirm => "Are you sure?") %>
          <%= link_to("", slideshow_group_setlist_path(@group, setlist), :class => "icon-play-circle") %>
        </td>
      </tr>
      <% i += 1 %>
      <% end %>
    </table>
  </div>
</div>

app/views/setlists/new.html.erb
<h2>New Setlist</h2>

<%= render "form" %>

app/views/setlists/show.html.erb
<% content_for :javascripts do %>
  <script type="text/javascript" charset="utf-8">
    $(function() {
      $( '#spotify-player' ).pin();
    });
  </script>
<% end %>

<%= render "setlist" %>

app/views/setlists/slideshow.html.erb
<% ( @full ? 1 : 2 ).times do |i| %>
  <div class="slideshow<%= " preview" if i == 0 && !@full %><%= " full" if @full %>">
    <div class="slideshow-clip">
      <div class="slideshow-view">
        <% @setlist.setlist_songs.each do |song| %>
          <% song.slides.each do |slide| %>
            <% if !slide.blank? %>
              <div class="slideshow-slide">
                <div class="slideshow-slide-content" style="white-space: pre"><%= slide %></div><br /><br />
              </div>
            <% end %>
          <% end %>
          <div class="slideshow-slide"><div class="slideshow-slide-content">&nbsp;</div></div>
          <div class="separator">
            <button class="button add-slide">+</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<% if !@full %>
  <div class="slideshow-backgrounds">
    <div class="slideshow-backgrounds-view">
      <% @backgrounds.each do |bg| %>
        <div class="slideshow-backgrounds-background" style="background-image: url(/assets/ss-backgrounds/<%= bg %>)">
        </div>
      <% end %>
    </div>
  </div>
  <div class="slideshow-backgrounds-background draggable"></div>
  <button class="button done-editing-slideshow">Done</button>
  <button class="button edit-slideshow">Edit</button>
  <button class="button start-slideshow">Start Slideshow</button>
<% end %>
<% content_for :javascripts do %>
  <script type="text/javascript" charset="utf-8">
    var Slideshow = {
      backgrounds: <%= raw @backgrounds.to_json %>
    };
  </script>
  <% if @full %>
    <script type="text/javascript" charset="utf-8">
      Slideshow.fullScreen = true;
    </script>
  <% end %>
  <%= javascript_include_tag "slideshow.js" %>
  <%= javascript_include_tag "mustache.js" %>
<% end %>

app/views/songs/edit.html.erb
<%= form_for(@song, :url => group_song_path(@group, @song)) do |f| %>
  <h1 class="page-header">
    Edit Song
    <%= f.submit "Save", :class => "btn btn-primary pull-right" %>
    <%= f.submit "Link to Spotify", :class => "btn btn-success pull-right" %>
  </h1>

  <%= render "form", :f => f %>
<% end %>

app/views/songs/index.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag "key.selector" %>
  <%= javascript_include_tag "setlists" %>
  <script type="text/javascript" charset="utf-8">
    var Setlister = Setlister || {};
    Setlister.groupPath = '<%= group_path(@group) %>';

    $( function() {
      $( '.key-selector' ).keySelector();
    });
  </script>
  <script type="text/mustache" id="flyout-template" charset="utf-8">
    <ul>
      <li class="head">Add to Setlist</li>
      {{# setlists }}
        <li data-id="{{ id }}">{{ title }}<i class="icon-refresh icon-spin"></i><i class="icon-ok"></i></li>
      {{/ setlists }}
    </ul>
  </script>
<% end %>

<h2 class="page-header">Songs<%= link_to "Add", new_group_song_path(@group), :class => "add button" %></h2>
<div class="builder">
  <div class="builder-inner">
    <table>
      <tr>
        <th width="50"></th>
        <th width="510">Name</th>
        <th width="500">Key</th>
        <th width="210">Actions</th>
      </tr>
      <% i = 1 %>
      <% @songs.each do |song| %>
      <tr>
        <td><%= i %>.</td>
        <td class="song-name"><%= link_to(song.title, group_song_path(@group, song)) %></td>
        <td class="key-selector" data-key="<%= song.data_key %>" data-song=""></td>
        <td class="actions">
          <%= link_to("", group_song_path(@group, song), :class => "icon-eye-open") %>
          <%= link_to("", edit_group_song_path(@group, song), :class => "icon-pencil") %>
          <%= link_to("", group_song_path(@group, song), :class => "icon-trash", :method => "delete", :confirm => "Are you sure?") %>
          <%= link_to("", "#", :class => "icon-plus-sign add-to-setlist-link", :"data-id" => song.id, :"data-key" => song.key) %>
        </td>
      </tr>
      <% i += 1 %>
      <% end %>
    </table>
  </div>
</div>

<%= render "layouts/flyout" %>

app/views/songs/new.html.erb
<%= form_for(@song, :url => group_songs_path(@group)) do |f| %>
  <h1 class="page-header">
    New Song
    <%= f.submit "Save", :class => "btn btn-primary pull-right" %>
    <%= f.submit "Link to Spotify", :class => "btn btn-success pull-right", :"data-toggle" => "modal", :"data-target" => "#spotify-modal" %>
  </h1>

  <%= render "form", :f => f %>
<% end %>

app/views/songs/show.html.erb
<div class="song">
  <h2><%= @song.title %></h2>
  <pre id="our-god-chords"><%= @song.text %></pre>
  <div class="meta">
    <%= @song.artist %> <%= !@song.year.blank? ? @song.year.strftime('%Y') : '' %>
    <span class="license"><%= @song.license %></span>
  </div>
</div>